application:
  appId: MAVEN-123
  assetId: MAVEN-123
  sdlcType: EDM
  appName: simple-java-maven-app
  appType: WebApplication
  webservice: false
  restApi: false
  microservice: false
  frameworks:
    - Java
  projectLanguage: Java
  buildSystem: Java
  riskMatrixRevision: Rev1.0
  sourceFilePattern: ".*\\+\\+\\+.*(\\.java|\\.jsp)+.*"
  sensitivePackagePattern: ".*(\\+\\+\\+.*(org\\/hdivsamples\\/security)).*"
  fileChangeThreshold: 20

environment:
  scm: "github"
  scmOwner: "evansa-synopsys"
  scmRepositoryName: "simple-java-maven-app"
  scmBranchName: master
  testDeploymentRoot: "vuLnDAP"
  defaultAppPortNumber: "8080"
  imChannelIdentifier: "#bd-alert"
  jiraProjectName: "MJ"
  jiraIssuesQuery: "resolution = \"Unresolved\" AND labels in (Security, Defect)"
  gitlabHostUrl: "https://github.com/"

